import React, { useState, useEffect } from 'react';
import Nav from '../Nav/Nav';
import axios from 'axios';
import jsPDF from 'jspdf';

const URL = 'http://localhost:5000/products';

function ProductManager() {
  // ------------------- STATES -------------------
  const [products, setProducts] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingProductId, setEditingProductId] = useState(null);

  // ------------------- SELECTED FIELDS FOR PDF -------------------
  const [selectedFields, setSelectedFields] = useState({
    product_name: true,
    price: true,
    description: true,
    photo: true,
    created_by: true
  });

  // ------------------- FORM INPUTS -------------------
  const defaultInputs = {
    product_name: '',
    price: '',
    description: '',
    photo: null,
    created_by: ''
  };

  const [inputs, setInputs] = useState(defaultInputs);
  const [editInputs, setEditInputs] = useState(defaultInputs);

  // ------------------- COMPANY INFORMATION -------------------
  const companyInfo = {
    name: 'SelfMe',
    tagline: 'FUTURE OF SUN - SOLAR POWER',
    address: ['No/346, Madalanda, Dompe,', 'Colombo, Sri Lanka'],
    phone: '+94 717 882 883',
    email: 'Selfmepvtltd@gmail.com',
    website: 'www.selfme.com'
  };

  // ------------------- FETCH PRODUCTS -------------------
  const fetchProducts = async () => {
    try {
      const res = await axios.get(URL);
      setProducts(res.data.products || []);
    } catch (err) {
      console.error('Error fetching products:', err);
      setProducts([]);
    }
  };

  useEffect(() => {
    fetchProducts();
  }, []);

  // ------------------- LOGO CONVERSION -------------------
  const getLogoAsBase64 = () => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        const base64 = canvas.toDataURL('image/png');
        resolve(base64);
      };
      img.onerror = () => {
        console.warn('Could not load logo, proceeding without it');
        resolve(null);
      };
      img.src = '/logo192.png';
    });
  };

  // ------------------- PROFESSIONAL PDF GENERATION -------------------
  const generatePDF = async (data, title) => {
    if (!data.length) return alert('No products to download!');

    try {
      const logoBase64 = await getLogoAsBase64();
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      const addLetterhead = () => {
        if (logoBase64) {
          doc.addImage(logoBase64, 'PNG', 15, 10, 30, 30);
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(28);
        doc.setTextColor(0, 0, 139);
        doc.text(companyInfo.name, logoBase64 ? 55 : pageWidth / 2, 25, { align: logoBase64 ? 'left' : 'center' });

        doc.setFontSize(12);
        doc.setTextColor(0, 128, 255);
        doc.text(companyInfo.tagline, logoBase64 ? 55 : pageWidth / 2, 35, { align: logoBase64 ? 'left' : 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text('Address:', 15, 50);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        companyInfo.address.forEach((line, index) => {
          doc.text(line, 15, 57 + (index * 7));
        });

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text('Contact Information:', pageWidth - 85, 50);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        doc.text(`Phone: ${companyInfo.phone}`, pageWidth - 85, 57);
        doc.text(`Email: ${companyInfo.email}`, pageWidth - 85, 64);
        doc.text(`Website: ${companyInfo.website}`, pageWidth - 85, 71);

        doc.setLineWidth(1.5);
        doc.setDrawColor(0, 0, 139);
        doc.line(15, 80, pageWidth - 15, 80);

        doc.setLineWidth(0.8);
        doc.setDrawColor(0, 128, 255);
        doc.line(15, 82, pageWidth - 15, 82);
      };

      const addFooter = (pageNum, totalPages) => {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);

        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);

        const footerText = `This document is generated by ${companyInfo.name} Product Management System`;
        doc.text(footerText, pageWidth / 2, pageHeight - 22, { align: 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 15, pageHeight - 12, { align: 'right' });
        const genDate = new Date().toLocaleDateString('en-GB');
        const genTime = new Date().toLocaleTimeString('en-GB', { hour12: false });
        doc.text(`Generated: ${genDate} at ${genTime}`, 15, pageHeight - 12);

        doc.setTextColor(0, 0, 139);
        doc.text(companyInfo.website, pageWidth / 2, pageHeight - 5, { align: 'center' });
      };

      let totalPages = 1;
      let tempY = 95;
      data.forEach(() => {
        let fieldsCount = Object.keys(selectedFields).filter(field => selectedFields[field]).length;
        let productHeight = Math.ceil(fieldsCount / 2) * 12 + 35;

        if (tempY + productHeight > pageHeight - 45) {
          totalPages++;
          tempY = 95;
        }
        tempY += productHeight;
      });

      let currentPage = 1;
      let y = 95;

      addLetterhead();

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(40, 40, 40);
      const titleText = title.toUpperCase();
      doc.text(titleText, pageWidth / 2, 90, { align: 'center' });

      data.forEach((product, idx) => {
        let fieldsCount = Object.keys(selectedFields).filter(field => selectedFields[field]).length;
        let productHeight = Math.ceil(fieldsCount / 2) * 12 + 35;

        if (y + productHeight > pageHeight - 45) {
          addFooter(currentPage, totalPages);
          doc.addPage();
          currentPage++;
          addLetterhead();
          y = 95;
        }

        doc.setFillColor(240, 248, 255);
        doc.rect(15, y - 3, pageWidth - 30, 18, 'F');

        doc.setLineWidth(0.8);
        doc.setDrawColor(0, 0, 139);
        doc.rect(15, y - 3, pageWidth - 30, 18);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 139);
        doc.text(`PRODUCT RECORD #${String(idx + 1).padStart(3, '0')}`, 20, y + 8);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(`Product ID: ${product.product_name || 'N/A'}`, pageWidth - 70, y + 8);

        y += 25;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);

        let leftY = y;
        let rightY = y;
        let isLeft = true;

        Object.keys(selectedFields).forEach(field => {
          if (selectedFields[field]) {
            let label = field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase());
            let value = field === 'photo' ? (product[field] ? 'Uploaded' : 'N/A') : (product[field] || 'N/A');

            if (typeof value === 'string' && value.length > 35) {
              value = value.substring(0, 32) + '...';
            }

            const x = isLeft ? 25 : pageWidth / 2 + 10;
            const currentY = isLeft ? leftY : rightY;

            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0, 0, 139);
            doc.text(`${label}:`, x, currentY);

            doc.setFont('helvetica', 'normal');
            doc.setTextColor(60, 60, 60);
            doc.text(String(value), x + 50, currentY);

            if (isLeft) {
              leftY += 12;
            } else {
              rightY += 12;
            }

            isLeft = !isLeft;
          }
        });

        y = Math.max(leftY, rightY) + 15;

        if (idx < data.length - 1) {
          doc.setLineWidth(0.3);
          doc.setDrawColor(220, 220, 220);
          doc.line(25, y - 5, pageWidth - 25, y - 5);
          y += 15;
        }
      });

      addFooter(currentPage, totalPages);

      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `${companyInfo.name}_${title.replace(/\s+/g, '_')}_${timestamp}.pdf`;

      doc.save(fileName);
      alert(`Professional report "${fileName}" downloaded successfully!`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    }
  };

  // ------------------- HANDLE INPUT CHANGE -------------------
  const handleChange = e => {
    if (e.target.name === 'photo') {
      setInputs(prev => ({ ...prev, photo: e.target.files[0] }));
    } else {
      setInputs(prev => ({ ...prev, [e.target.name]: e.target.value }));
    }
  };

  const handleEditChange = e => {
    if (e.target.name === 'photo') {
      setEditInputs(prev => ({ ...prev, photo: e.target.files[0] }));
    } else {
      setEditInputs(prev => ({ ...prev, [e.target.name]: e.target.value }));
    }
  };

  // ------------------- ADD PRODUCT -------------------
  const handleAddProduct = async e => {
    e.preventDefault();
    try {
      const formData = new FormData();
      Object.keys(inputs).forEach(key => {
        if (inputs[key] !== null) formData.append(key, inputs[key]);
      });

      const res = await axios.post(URL, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      setProducts([...products, res.data.product]);
      setInputs(defaultInputs);
      setShowAddForm(false);
      alert('Product added successfully!');
      window.location.reload();
    } catch (err) {
      console.error('Error adding product:', err);
      alert('Failed to add product!');
    }
  };

  // ------------------- EDIT PRODUCT -------------------
  const startEdit = product => {
    setEditingProductId(product._id);
    setEditInputs({
      product_name: product.product_name,
      price: product.price,
      description: product.description,
      photo: null,
      created_by: product.created_by
    });
  };

  const handleUpdateProduct = async e => {
    e.preventDefault();
    try {
      const formData = new FormData();
      Object.keys(editInputs).forEach(key => {
        if (editInputs[key] !== null) formData.append(key, editInputs[key]);
      });

      const res = await axios.put(`${URL}/${editingProductId}`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      setProducts(products.map(p => (p._id === editingProductId ? res.data.product : p)));
      setEditingProductId(null);
      setEditInputs(defaultInputs);
      alert('Product updated successfully!');
      window.location.reload();
    } catch (err) {
      console.error('Error updating product:', err);
      alert('Failed to update product!');
    }
  };

  // ------------------- DELETE PRODUCT -------------------
  const handleDeleteProduct = async id => {
    if (!window.confirm('Are you sure you want to delete this product?')) return;
    try {
      await axios.delete(`${URL}/${id}`);
      setProducts(products.filter(p => p._id !== id));
      alert('Product deleted successfully!');
    } catch (err) {
      console.error('Error deleting product:', err);
      alert('Failed to delete product!');
    }
  };

  // ------------------- DOWNLOAD FUNCTIONS -------------------
  const handleDownloadAll = () => generatePDF(products, 'Complete Product Directory Report');
  const handleDownloadSingle = product => generatePDF([product], `Individual Product Report - ${product.product_name}`);

  // ------------------- FILTERED PRODUCTS -------------------
  const filteredProducts = products.filter(product =>
    (product.product_name?.toLowerCase() || '').includes(searchTerm.toLowerCase())
  );

  // ------------------- RENDER -------------------
  return (
    <div className="users-section">
      <Nav />
      <div className="title-container">
        <h2 className="Title">Product Management System</h2>
        <p className="subtitle">{companyInfo.name} - {companyInfo.tagline}</p>
      </div>

      <button className="add-user-toggle" onClick={() => setShowAddForm(!showAddForm)}>
        {showAddForm ? '✕ Hide Add Product Form' : '➕ Show Add Product Form'}
      </button>

      {showAddForm && (
        <div className="add-user-container">
          <h3>📝 Add New Product</h3>
          <form className="add-user-form" onSubmit={handleAddProduct}>
            {Object.keys(defaultInputs).map(field => (
              <div className="form-group" key={field}>
                <label htmlFor={field}>{field.replace('_', ' ').toUpperCase()}</label>
                <input
                  type={field === 'photo' ? 'file' : field === 'price' || field === 'created_by' ? 'number' : 'text'}
                  id={field}
                  name={field}
                  placeholder={`Enter ${field.replace('_', ' ')}`}
                  value={field !== 'photo' ? inputs[field] : undefined}
                  onChange={handleChange}
                  required={field === 'product_name' || field === 'price' || field === 'created_by'}
                />
              </div>
            ))}
            <button type="submit" className="submit-btn">Add Product</button>
          </form>
        </div>
      )}

      <div className="search-bar">
        <input
          type="text"
          placeholder="🔍 Search by Product Name..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="download-options professional-section">
        <h3>📄 Professional Report Generation</h3>
        <p>Select the fields to include in your professional letterhead report:</p>
        <div className="field-checkboxes">
          {Object.keys(selectedFields).map(field => (
            <label key={field} className="checkbox-label">
              <input
                type="checkbox"
                checked={selectedFields[field]}
                onChange={() => setSelectedFields(prev => ({ ...prev, [field]: !prev[field] }))}
              />
              <span>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</span>
            </label>
          ))}
        </div>
        <div className="download-buttons">
          <button className="download-all-btn" onClick={handleDownloadAll}>
            📊 Download Complete Directory ({products.length} products)
          </button>
          <p className="download-note">
            Reports include professional letterhead with {companyInfo.name} logo, contact details, and formatted layouts.
          </p>
        </div>
      </div>

      <div className="users-table-container">
        <div className="table-header">
          <span className="table-user-count">👥 Total Products: {products.length}</span>
          <span className="filtered-count">
            {searchTerm && `(Showing ${filteredProducts.length} filtered results)`}
          </span>
        </div>
        <table className="users-table">
          <thead>
            <tr>
              {Object.keys(defaultInputs).map(field => (
                <th key={field}>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</th>
              ))}
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredProducts.map(product => (
              <tr key={product._id}>
                {editingProductId === product._id ? (
                  <td colSpan={Object.keys(defaultInputs).length + 1}>
                    <div className="update-user-container">
                      <h1>✏️ Update Product Information</h1>
                      <form onSubmit={handleUpdateProduct}>
                        {Object.keys(defaultInputs).map(field => (
                          <div className="form-group" key={field}>
                            <label htmlFor={field}>{field.replace('_', ' ').toUpperCase()}</label>
                            <input
                              type={field === 'photo' ? 'file' : field === 'price' || field === 'created_by' ? 'number' : 'text'}
                              name={field}
                              placeholder={field.replace('_', ' ').toUpperCase()}
                              value={field !== 'photo' ? editInputs[field] : undefined}
                              onChange={handleEditChange}
                              required={field === 'product_name' || field === 'price' || field === 'created_by'}
                            />
                          </div>
                        ))}
                        <button type="submit" className="submit-btn">✅ Update Product</button>
                        <button type="button" className="cancel-button" onClick={() => setEditingProductId(null)}>❌ Cancel</button>
                      </form>
                    </div>
                  </td>
                ) : (
                  <>
                    {Object.keys(defaultInputs).map(field => (
                      <td key={field}>
                        {field === 'photo' && product[field] ? (
                          <img src={`http://localhost:5000${product[field]}`} alt="product" width="60" />
                        ) : (
                          product[field] || 'N/A'
                        )}
                      </td>
                    ))}
                    <td className="actions-cell">
                      <button className="action-btn edit-btn" onClick={() => startEdit(product)} title="Edit Product">
                        ✏️
                      </button>
                      <button className="action-btn delete-btn" onClick={() => handleDeleteProduct(product._id)} title="Delete Product">
                        🗑️
                      </button>
                      <button className="action-btn download-btn" onClick={() => handleDownloadSingle(product)} title="Download Product Report">
                        📄
                      </button>
                    </td>
                  </>
                )}
              </tr>
            ))}
          </tbody>
        </table>

        {filteredProducts.length === 0 && (
          <div className="no-users-message">
            <p>📭 No products found matching your search criteria.</p>
            {searchTerm && (
              <button className="clear-search-btn" onClick={() => setSearchTerm('')}>
                Clear Search
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default ProductManager;