import React, { useState, useEffect } from 'react';
import Nav from '../Nav/Nav';
import axios from 'axios';
import jsPDF from 'jspdf';
import './Users.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const URL = `${API}/users`;


function Users() {
  // ------------------- STATES -------------------
  const [users, setUsers] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFields, setSelectedFields] = useState({
    reg_no: true,
    shop_owner_name: true,
    shop_name: true,
    phone_number: true,
    created_at: true
  });
  const [inputs, setInputs] = useState({
    reg_no: '', shop_owner_name: '', shop_name: '',
    phone_number: ''
  });
  const [addPhoneError, setAddPhoneError] = useState('');
  const [showAddUserForm, setShowAddUserForm] = useState(false);
  const [editingUserId, setEditingUserId] = useState(null);
  const [editInputs, setEditInputs] = useState({
    reg_no: '', shop_owner_name: '', shop_name: '',
    phone_number: ''
  });
  const [editPhoneError, setEditPhoneError] = useState('');
  // ------------------- COMPANY INFORMATION -------------------
  const companyInfo = {
    name: 'Dompe',
    tagline: 'Dompe',
    address: ['No/346, Madalanda, Dompe,', 'Colombo, Sri Lanka'],
    phone: '+94 000 000 0000',
    email: 'test@gmail.com',
    website: 'www.test.com'
  };
  // ------------------- FETCH USERS -------------------
  const fetchUsers = async () => {
    try {
      const res = await axios.get(URL);
      setUsers(res.data.shops || []);
    } catch (err) {
      console.error('Error fetching users:', err);
      setUsers([]);
    }
  };
  useEffect(() => {
    fetchUsers();
  }, []);
  // ------------------- LOGO CONVERSION -------------------
  const getLogoAsBase64 = () => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        const base64 = canvas.toDataURL('image/png');
        resolve(base64);
      };
      img.onerror = () => {
        console.warn('Could not load logo, proceeding without it');
        resolve(null);
      };
      // Update this path to match your logo location
      img.src = '/logo192.png';
    });
  };
  // ------------------- PROFESSIONAL PDF GENERATION -------------------
  const generatePDF = async (data, title) => {
  if (!data.length) return alert('No users to download!');

  try {
    const logoBase64 = await getLogoAsBase64();
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Function to add professional letterhead
    const addLetterhead = () => {
      if (logoBase64) {
        doc.addImage(logoBase64, 'PNG', 15, 10, 30, 30);
      }
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(28);
      doc.setTextColor(0, 0, 139);
      doc.text(companyInfo.name, logoBase64 ? 55 : pageWidth / 2, 25, { align: logoBase64 ? 'left' : 'center' });
      
      doc.setFontSize(12);
      doc.setTextColor(0, 128, 255);
      doc.text(companyInfo.tagline, logoBase64 ? 55 : pageWidth / 2, 35, { align: logoBase64 ? 'left' : 'center' });
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 139);
      doc.text('Address:', 15, 50);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      companyInfo.address.forEach((line, index) => {
        doc.text(line, 15, 57 + (index * 7));
      });
      
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 139);
      doc.text('Contact Information:', pageWidth - 85, 50);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.text(`Phone: ${companyInfo.phone}`, pageWidth - 85, 57);
      doc.text(`Email: ${companyInfo.email}`, pageWidth - 85, 64);
      doc.text(`Website: ${companyInfo.website}`, pageWidth - 85, 71);
      
      doc.setLineWidth(1.5);
      doc.setDrawColor(0, 0, 139);
      doc.line(15, 80, pageWidth - 15, 80);
      
      doc.setLineWidth(0.8);
      doc.setDrawColor(0, 128, 255);
      doc.line(15, 82, pageWidth - 15, 82);
    };
    
    const addFooter = (pageNum, totalPages) => {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      
      doc.setLineWidth(0.5);
      doc.setDrawColor(200, 200, 200);
      doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);
      
      const footerText = `This document is generated by ${companyInfo.name} User Management System`;
      doc.text(footerText, pageWidth / 2, pageHeight - 22, { align: 'center' });
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 15, pageHeight - 12, { align: 'right' });
      const genDate = new Date().toLocaleDateString('en-GB');
      const genTime = new Date().toLocaleTimeString('en-GB', { hour12: false });
      doc.text(`Generated: ${genDate} at ${genTime}`, 15, pageHeight - 12);
      
      doc.setTextColor(0, 0, 139);
      doc.text(companyInfo.website, pageWidth / 2, pageHeight - 5, { align: 'center' });
    };

    // Check if this is a complete directory (multiple users) or single user
    const isCompleteDirectory = data.length > 1;

    if (isCompleteDirectory) {
      // TABLE FORMAT for complete directory
      
      // Calculate total pages
      const rowsPerPage = 22;
      const totalPages = Math.ceil(data.length / rowsPerPage) || 1;

      let currentPage = 1;
      let y = 95;

      // Add first page
      addLetterhead();

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text(title.toUpperCase(), pageWidth / 2, 90, { align: 'center' });

      y = 100;

      // Table configuration
      const startX = 10;
      const colWidths = {
        no: 12,
        reg_no: 20,
        shop_owner: 45,
        shop_name: 45,
        phone: 35,
        date: 33
      };

      // Draw table header
      const drawTableHeader = () => {
        doc.setFillColor(0, 0, 139);
        doc.rect(startX, y, pageWidth - 20, 10, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(255, 255, 255);

        let x = startX + 2;
        doc.text('No.', x, y + 7);
        x += colWidths.no;
        doc.text('Reg. No', x, y + 7);
        x += colWidths.reg_no;
        doc.text('Shop Owner Name', x, y + 7);
        x += colWidths.shop_owner;
        doc.text('Shop Name', x, y + 7);
        x += colWidths.shop_name;
        doc.text('Phone Number', x, y + 7);
        x += colWidths.phone;
        doc.text('Created Date', x, y + 7);

        y += 10;
      };

      drawTableHeader();

      // Draw table rows
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(60, 60, 60);

      data.forEach((user, idx) => {
        // Check if we need a new page
        if (y > pageHeight - 50) {
          addFooter(currentPage, totalPages);
          doc.addPage();
          currentPage++;
          addLetterhead();
          y = 100;
          drawTableHeader();
        }

        // Alternate row colors
        if (idx % 2 === 0) {
          doc.setFillColor(248, 249, 250);
          doc.rect(startX, y, pageWidth - 20, 9, 'F');
        }

        // Draw cell borders
        doc.setDrawColor(220, 220, 220);
        doc.setLineWidth(0.1);
        let x = startX;
        
        // Draw vertical lines
        for (let i = 0; i <= Object.keys(colWidths).length; i++) {
          doc.line(x, y, x, y + 9);
          if (i < Object.keys(colWidths).length) {
            x += Object.values(colWidths)[i];
          }
        }
        
        // Draw horizontal line
        doc.line(startX, y + 9, pageWidth - 10, y + 9);

        // Add text content
        x = startX + 2;
        
        // Truncate long text to fit
        const truncate = (text, maxLength) => {
          text = String(text || '');
          return text.length > maxLength ? text.substring(0, maxLength - 2) + '..' : text;
        };

        doc.text(String(idx + 1), x, y + 6);
        x += colWidths.no;
        doc.text(truncate(user.reg_no, 12), x, y + 6);
        x += colWidths.reg_no;
        doc.text(truncate(user.shop_owner_name, 28), x, y + 6);
        x += colWidths.shop_owner;
        doc.text(truncate(user.shop_name, 28), x, y + 6);
        x += colWidths.shop_name;
        doc.text(truncate(user.phone_number, 20), x, y + 6);
        x += colWidths.phone;
        doc.text(user.created_at ? new Date(user.created_at).toLocaleDateString('en-GB') : 'N/A', x, y + 6);

        y += 9;
      });

      // Summary section
      y += 5;
      if (y > pageHeight - 60) {
        addFooter(currentPage, totalPages);
        doc.addPage();
        currentPage++;
        addLetterhead();
        y = 100;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 139);
      
      doc.setFillColor(230, 240, 255);
      doc.rect(startX, y, pageWidth - 20, 12, 'F');
      doc.setDrawColor(0, 0, 139);
      doc.setLineWidth(0.5);
      doc.rect(startX, y, pageWidth - 20, 12);

      doc.text(`TOTAL SHOPS REGISTERED: ${data.length}`, startX + 5, y + 8);
      doc.text(`Report Generated: ${new Date().toLocaleDateString('en-GB')}`, pageWidth - 85, y + 8);

      addFooter(currentPage, totalPages);

    } else {
      // DETAILED FORMAT for single user
      const user = data[0];

      addLetterhead();

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(40, 40, 40);
      const titleText = title.toUpperCase();
      doc.text(titleText, pageWidth / 2, 90, { align: 'center' });

      let y = 105;

      // User Details Header
      doc.setFillColor(240, 248, 255);
      doc.rect(15, y - 3, pageWidth - 30, 18, 'F');
      doc.setLineWidth(0.8);
      doc.setDrawColor(0, 0, 139);
      doc.rect(15, y - 3, pageWidth - 30, 18);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 139);
      doc.text('SHOP INFORMATION', 20, y + 8);

      y += 25;

      // User Details Table
      const startX = 15;
      const tableWidth = pageWidth - 30;
      const labelWidth = 70;
      const valueWidth = tableWidth - labelWidth;

      const userDetails = [
        { label: 'Registration Number', value: user.reg_no },
        { label: 'Shop Owner Name', value: user.shop_owner_name },
        { label: 'Shop Name', value: user.shop_name },
        { label: 'Phone Number', value: user.phone_number },
        { label: 'Created Date', value: user.created_at ? new Date(user.created_at).toLocaleDateString('en-GB') : 'N/A' },
        { label: 'Created Time', value: user.created_at ? new Date(user.created_at).toLocaleTimeString('en-GB', { hour12: false }) : 'N/A' }
      ];

      // Draw details table
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      userDetails.forEach((detail, idx) => {
        // Alternate row colors
        if (idx % 2 === 0) {
          doc.setFillColor(248, 249, 250);
          doc.rect(startX, y, tableWidth, 12, 'F');
        }

        // Draw borders
        doc.setDrawColor(220, 220, 220);
        doc.setLineWidth(0.1);
        
        // Horizontal lines
        doc.line(startX, y, startX + tableWidth, y);
        doc.line(startX, y + 12, startX + tableWidth, y + 12);
        
        // Vertical lines
        doc.line(startX, y, startX, y + 12);
        doc.line(startX + labelWidth, y, startX + labelWidth, y + 12);
        doc.line(startX + tableWidth, y, startX + tableWidth, y + 12);

        // Add label (bold)
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text(detail.label, startX + 3, y + 8);

        // Add value (normal)
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        const value = String(detail.value || 'N/A');
        doc.text(value.length > 50 ? value.substring(0, 47) + '...' : value, startX + labelWidth + 3, y + 8);

        y += 12;
      });

      // Add border for last row
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.5);
      doc.rect(startX, y - (userDetails.length * 12), tableWidth, userDetails.length * 12);

      y += 15;

      // Additional Information Section
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 139);
      doc.text('ADDITIONAL NOTES', startX, y);
      y += 10;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.setFillColor(252, 252, 252);
      doc.rect(startX, y, tableWidth, 25, 'F');
      doc.setDrawColor(220, 220, 220);
      doc.rect(startX, y, tableWidth, 25);

      doc.text('This shop record was created on ' + (user.created_at ? new Date(user.created_at).toLocaleDateString('en-GB', { 
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
      }) : 'N/A'), startX + 5, y + 8);
      doc.text('For any updates or inquiries, please contact the administration.', startX + 5, y + 16);

      addFooter(1, 1);
    }

    const timestamp = new Date().toISOString().split('T')[0];
    const fileName = `${companyInfo.name}_${title.replace(/\s+/g, '_')}_${timestamp}.pdf`;

    doc.save(fileName);
    alert(`Professional report "${fileName}" downloaded successfully!`);

  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Error generating PDF. Please try again.');
  }
};
  // ------------------- ADD USER -------------------
  const handleChange = e => {
    const { name, value } = e.target;
    if (name === 'phone_number') {
      const digitsOnly = value.replace(/\D/g, '');
      setInputs(prev => ({ ...prev, [name]: digitsOnly }));
      if (digitsOnly.length > 10) {
        setAddPhoneError('Phone number cannot exceed 10 digits');
      } else {
        setAddPhoneError(digitsOnly.length === 10 ? '' : 'Phone number must be exactly 10 digits');
      }
    } else {
      setInputs(prev => ({ ...prev, [name]: value }));
    }
  };
  const handleAddUser = async e => {
    e.preventDefault();
    if (inputs.phone_number.length !== 10) {
      setAddPhoneError('Phone number must be exactly 10 digits');
      return;
    }
    try {
      const res = await axios.post(URL, { ...inputs });
      setUsers([...users, res.data.shop]);
      setInputs({ reg_no: '', shop_owner_name: '', shop_name: '', phone_number: '' });
      setAddPhoneError('');
      setShowAddUserForm(false);
      alert('User added successfully!');
      window.location.reload();
    } catch (err) {
      console.error('Error adding user:', err);
      alert('Failed to add user!');
    }
  };
  // Auto-set next Reg. No when showing add form
  useEffect(() => {
    if (showAddUserForm) {
      const maxReg = users.length > 0 ? Math.max(...users.map(u => parseInt(u.reg_no) || 0)) + 1 : 1;
      setInputs(prev => ({ ...prev, reg_no: maxReg.toString() }));
    }
  }, [showAddUserForm, users]);
  // ------------------- EDIT / UPDATE USER -------------------
  const startEdit = user => {
    setEditingUserId(user._id);
    setEditInputs({ ...user });
    setEditPhoneError('');
  };
  const handleEditChange = e => {
    const { name, value } = e.target;
    if (name === 'phone_number') {
      const digitsOnly = value.replace(/\D/g, '');
      setEditInputs(prev => ({ ...prev, [name]: digitsOnly }));
      if (digitsOnly.length > 10) {
        setEditPhoneError('Phone number cannot exceed 10 digits');
      } else {
        setEditPhoneError(digitsOnly.length === 10 ? '' : 'Phone number must be exactly 10 digits');
      }
    } else {
      setEditInputs(prev => ({ ...prev, [name]: value }));
    }
  };
  const handleUpdateUser = async e => {
    e.preventDefault();
    if (editInputs.phone_number.length !== 10) {
      setEditPhoneError('Phone number must be exactly 10 digits');
      return;
    }
    try {
      const res = await axios.put(`${URL}/${editingUserId}`, { ...editInputs });
      setUsers(users.map(u => (u._id === editingUserId ? res.data.shop : u)));
      setEditingUserId(null);
      setEditInputs({ reg_no: '', shop_owner_name: '', shop_name: '', phone_number: '' });
      setEditPhoneError('');
      alert('User updated successfully!');
      window.location.reload();
    } catch (err) {
      console.error('Error updating user:', err);
      alert('Failed to update user!');
    }
  };
  // ------------------- DELETE USER -------------------
  const handleDeleteUser = async id => {
    if (!window.confirm('Are you sure you want to delete this user?')) return;
    try {
      await axios.delete(`${URL}/${id}`);
      setUsers(users.filter(u => u._id !== id));
      alert('User deleted successfully!');
    } catch (err) {
      console.error('Error deleting user:', err);
      alert('Failed to delete user!');
    }
  };
  // ------------------- DOWNLOAD FUNCTIONS -------------------
  const handleDownloadAll = () => generatePDF(users, 'Complete Shop Directory Report');
  const handleDownloadSingle = user => generatePDF([user], `Individual Shop Report - ${user.shop_name || user.shop_owner_name}`);
  // ------------------- FILTERED USERS -------------------
  const filteredUsers = users.filter(user =>
    (user.shop_owner_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (user.shop_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (user.phone_number?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (user.reg_no?.toString() || '').includes(searchTerm)
  );
  // ------------------- RENDER -------------------
  return (
    <div className="users-section" id="users-section">
      <Nav />
      <div className="title-container">
        <h2 className="Title">Add the shop to the Systems</h2>
        <p className="subtitle">{companyInfo.name} - {companyInfo.tagline}</p>
      </div>
      <button className="add-user-toggle" onClick={() => setShowAddUserForm(!showAddUserForm)}>
        {showAddUserForm ? '✕ Hide Add User Form' : '➕ Show Add User Form'}
      </button>
      {showAddUserForm && (
        <div className="add-user-container">
          <h3>📝 Add New User</h3>
          <form className="add-user-form" onSubmit={handleAddUser}>
            {['reg_no', 'shop_owner_name', 'shop_name', 'phone_number'].map(field => (
              <div className="form-group" key={field}>
                <label htmlFor={field}>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</label>
                <input
                  type={field === 'phone_number' ? 'tel' : 'text'}
                  id={field}
                  name={field}
                  placeholder={`Enter ${field.replace('_', ' ')}`}
                  value={inputs[field]}
                  onChange={handleChange}
                  required
                  readOnly={field === 'reg_no'}
                  maxLength={field === 'phone_number' ? 10 : undefined}
                />
                {field === 'phone_number' && addPhoneError && <p className="error">{addPhoneError}</p>}
              </div>
            ))}
            <button type="submit" className="submit-btn">Add User</button>
          </form>
        </div>
      )}
      <div className="search-bar">
        <input
          type="text"
          placeholder="🔍 Search by Shop Owner Name, Shop Name, Phone Number or Reg. No..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
        />
      </div>
      {/* Enhanced Download Options */}
      <div className="download-options professional-section">
        <h3>📄 Professional Report Generation</h3>
        <p>Select the fields to include in your professional letterhead report:</p>
        <div className="field-checkboxes">
          {Object.keys(selectedFields).map(field => (
            <label key={field} className="checkbox-label">
              <input
                type="checkbox"
                checked={selectedFields[field]}
                onChange={() => setSelectedFields(prev => ({ ...prev, [field]: !prev[field] }))}
              />
              <span>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</span>
            </label>
          ))}
        </div>
        <div className="download-buttons">
          <button className="download-all-btn" onClick={handleDownloadAll}>
            📊 Download Complete Directory ({users.length} users)
          </button>
          <p className="download-note">
            Reports include professional letterhead with {companyInfo.name} logo, contact details, and formatted layouts.
          </p>
        </div>
      </div>
      {/* Users Table */}
      <div className="users-table-container">
        <div className="table-header">
          <span className="table-user-count">👥 Total Users: {users.length}</span>
          <span className="filtered-count">
            {searchTerm && `(Showing ${filteredUsers.length} filtered results)`}
          </span>
        </div>
        <table className="users-table">
          <thead>
            <tr>
              <th>Reg. No</th>
              <th>Shop Owner Name</th>
              <th>Shop Name</th>
              <th>Phone Number</th>
              <th>Created At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredUsers.map(user => (
              <tr key={user._id}>
                {editingUserId === user._id ? (
                  <td colSpan="6">
                    <div className="update-user-container">
                      <h1>✏️ Update User Information</h1>
                      <form onSubmit={handleUpdateUser}>
                        {['reg_no', 'shop_owner_name', 'shop_name', 'phone_number'].map(field => (
                          <div key={field}>
                            <input
                              type={field === 'phone_number' ? 'tel' : 'text'}
                              name={field}
                              placeholder={field.replace('_', ' ').toUpperCase()}
                              value={editInputs[field]}
                              onChange={handleEditChange}
                              required
                              readOnly={field === 'reg_no'}
                              maxLength={field === 'phone_number' ? 10 : undefined}
                            />
                            {field === 'phone_number' && editPhoneError && <p className="error">{editPhoneError}</p>}
                          </div>
                        ))}
                        <button type="submit">✅ Update User</button>
                        <button type="button" className="cancel-button" onClick={() => setEditingUserId(null)}>❌ Cancel</button>
                      </form>
                    </div>
                  </td>
                ) : (
                  <>
                    <td><strong>{user.reg_no}</strong></td>
                    <td>{user.shop_owner_name}</td>
                    <td>{user.shop_name}</td>
                    <td>{user.phone_number}</td>
                    <td>{user.created_at ? new Date(user.created_at).toLocaleDateString('en-GB') : 'N/A'}</td>
                    <td className="actions-cell">
                      <button className="action-btn edit-btn" onClick={() => startEdit(user)} title="Edit User">
                        ✏️
                      </button>
                      <button className="action-btn delete-btn" onClick={() => handleDeleteUser(user._id)} title="Delete User">
                        🗑️
                      </button>
                      <button className="action-btn download-btn" onClick={() => handleDownloadSingle(user)} title="Download User Report">
                        📄
                      </button>
                    </td>
                  </>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      
        {filteredUsers.length === 0 && (
          <div className="no-users-message">
            <p>📭 No users found matching your search criteria.</p>
            {searchTerm && (
              <button className="clear-search-btn" onClick={() => setSearchTerm('')}>
                Clear Search
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
export default Users;