// FundsManagement.jsx (Updated)
import React, { useState, useEffect } from 'react';
import Nav from '../Nav/Nav';
import axios from 'axios';
import jsPDF from 'jspdf';
import './FundsManagement.css';

const URL = 'http://localhost:5000/funds'; // Matches new backend endpoint

function FundsManagement() {
  // ------------------- STATES -------------------
  const [fundsData, setFundsData] = useState([]); // Array of {user: {...}, funds: [...]}
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFields, setSelectedFields] = useState({
    reg_no: true,
    shop_owner_name: true,
    shop_name: true,
    phone_number: true,
    created_at: true,
    year: true,
    month: true,
    cash: true,
    funds_created_at: true
  });
  const [loading, setLoading] = useState(true); // Added loading state

  // No add/edit/delete for this view, as it's read-only details

  // ------------------- COMPANY INFORMATION -------------------
  const companyInfo = {
    name: 'Dompe',
    tagline: 'Dompe',
    address: ['No/346, Madalanda, Dompe,', 'Colombo, Sri Lanka'],
    phone: '+94 000 000 0000',
    email: 'test@gmail.com',
    website: 'www.test.com'
  };

  // ------------------- FETCH JOINED DATA -------------------
  const fetchFundsData = async () => {
    try {
      setLoading(true);
      const res = await axios.get(URL);
      setFundsData(res.data.shops || []);
    } catch (err) {
      console.error('Error fetching funds data:', err);
      setFundsData([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFundsData();
  }, []);

  // ------------------- LOGO CONVERSION -------------------
  const getLogoAsBase64 = () => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        const base64 = canvas.toDataURL('image/png');
        resolve(base64);
      };
      img.onerror = () => {
        console.warn('Could not load logo, proceeding without it');
        resolve(null);
      };
      img.src = '/logo192.png';
    });
  };

  // ------------------- PROFESSIONAL PDF GENERATION -------------------
 const generatePDF = async (data, title) => {
  if (!data.length) return alert('No funds data to download!');
  try {
    const logoBase64 = await getLogoAsBase64();

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Month names helper
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const getMonthName = (monthNum) => monthNames[monthNum - 1] || monthNum.toString();

    // Function to add professional letterhead
    const addLetterhead = () => {
      if (logoBase64) {
        doc.addImage(logoBase64, 'PNG', 15, 10, 30, 30);
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(28);
      doc.setTextColor(0, 0, 139);
      doc.text(companyInfo.name, logoBase64 ? 55 : pageWidth / 2, 25, { align: logoBase64 ? 'left' : 'center' });

      doc.setFontSize(12);
      doc.setTextColor(0, 128, 255);
      doc.text(companyInfo.tagline, logoBase64 ? 55 : pageWidth / 2, 35, { align: logoBase64 ? 'left' : 'center' });

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 139);
      doc.text('Address:', 15, 50);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      companyInfo.address.forEach((line, index) => {
        doc.text(line, 15, 57 + (index * 7));
      });

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 139);
      doc.text('Contact Information:', pageWidth - 85, 50);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.text(`Phone: ${companyInfo.phone}`, pageWidth - 85, 57);
      doc.text(`Email: ${companyInfo.email}`, pageWidth - 85, 64);
      doc.text(`Website: ${companyInfo.website}`, pageWidth - 85, 71);

      doc.setLineWidth(1.5);
      doc.setDrawColor(0, 0, 139);
      doc.line(15, 80, pageWidth - 15, 80);

      doc.setLineWidth(0.8);
      doc.setDrawColor(0, 128, 255);
      doc.line(15, 82, pageWidth - 15, 82);
    };

    const addFooter = (pageNum, totalPages) => {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);

      doc.setLineWidth(0.5);
      doc.setDrawColor(200, 200, 200);
      doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);

      const footerText = `This document is generated by ${companyInfo.name} Funds Management System`;
      doc.text(footerText, pageWidth / 2, pageHeight - 22, { align: 'center' });

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 15, pageHeight - 12, { align: 'right' });
      const genDate = new Date().toLocaleDateString('en-GB');
      const genTime = new Date().toLocaleTimeString('en-GB', { hour12: false });
      doc.text(`Generated: ${genDate} at ${genTime}`, 15, pageHeight - 12);

      doc.setTextColor(0, 0, 139);
      doc.text(companyInfo.website, pageWidth / 2, pageHeight - 5, { align: 'center' });
    };

    // Check if this is a complete directory (multiple shops) or single shop
    const isCompleteDirectory = data.length > 1;

    if (isCompleteDirectory) {
      // TABLE FORMAT for complete directory
      
      // Flatten data for table
      const tableData = [];
      data.forEach(entry => {
        const user = entry.user;
        const funds = entry.funds || [];
        
        if (funds.length > 0) {
          funds.forEach(fund => {
            tableData.push({
              reg_no: user.reg_no,
              shop_owner: user.shop_owner_name,
              shop_name: user.shop_name,
              phone: user.phone_number,
              year: fund.year,
              months: fund.month ? fund.month.map(m => getMonthName(m)).join(', ') : 'N/A',
              cash: `LKR ${fund.cash || 0}`,
              date: new Date(fund.created_at).toLocaleDateString('en-GB')
            });
          });
        } else {
          tableData.push({
            reg_no: user.reg_no,
            shop_owner: user.shop_owner_name,
            shop_name: user.shop_name,
            phone: user.phone_number,
            year: 'N/A',
            months: 'N/A',
            cash: 'N/A',
            date: new Date(user.created_at).toLocaleDateString('en-GB')
          });
        }
      });

      // Calculate total pages
      const rowsPerPage = 20;
      const totalPages = Math.ceil(tableData.length / rowsPerPage) || 1;

      let currentPage = 1;
      let y = 95;

      // Add first page
      addLetterhead();

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text(title.toUpperCase(), pageWidth / 2, 90, { align: 'center' });

      y = 100;

      // Table configuration
      const startX = 10;
      const colWidths = {
        reg_no: 15,
        shop_owner: 30,
        shop_name: 30,
        phone: 25,
        year: 15,
        months: 30,
        cash: 25,
        date: 20
      };

      // Draw table header
      const drawTableHeader = () => {
        doc.setFillColor(0, 0, 139);
        doc.rect(startX, y, pageWidth - 20, 10, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(255, 255, 255);

        let x = startX + 2;
        doc.text('Reg', x, y + 7);
        x += colWidths.reg_no;
        doc.text('Shop Owner', x, y + 7);
        x += colWidths.shop_owner;
        doc.text('Shop Name', x, y + 7);
        x += colWidths.shop_name;
        doc.text('Phone', x, y + 7);
        x += colWidths.phone;
        doc.text('Year', x, y + 7);
        x += colWidths.year;
        doc.text('Months', x, y + 7);
        x += colWidths.months;
        doc.text('Cash', x, y + 7);
        x += colWidths.cash;
        doc.text('Date', x, y + 7);

        y += 10;
      };

      drawTableHeader();

      // Draw table rows
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(60, 60, 60);

      tableData.forEach((row, idx) => {
        // Check if we need a new page
        if (y > pageHeight - 50) {
          addFooter(currentPage, totalPages);
          doc.addPage();
          currentPage++;
          addLetterhead();
          y = 100;
          drawTableHeader();
        }

        // Alternate row colors
        if (idx % 2 === 0) {
          doc.setFillColor(248, 249, 250);
          doc.rect(startX, y, pageWidth - 20, 8, 'F');
        }

        // Draw cell borders
        doc.setDrawColor(220, 220, 220);
        doc.setLineWidth(0.1);
        let x = startX;
        
        // Draw vertical lines
        for (let i = 0; i <= Object.keys(colWidths).length; i++) {
          doc.line(x, y, x, y + 8);
          if (i < Object.keys(colWidths).length) {
            x += Object.values(colWidths)[i];
          }
        }
        
        // Draw horizontal line
        doc.line(startX, y + 8, pageWidth - 10, y + 8);

        // Add text content
        x = startX + 2;
        
        // Truncate long text to fit
        const truncate = (text, maxLength) => {
          text = String(text || '');
          return text.length > maxLength ? text.substring(0, maxLength - 2) + '..' : text;
        };

        doc.text(truncate(row.reg_no, 8), x, y + 5.5);
        x += colWidths.reg_no;
        doc.text(truncate(row.shop_owner, 18), x, y + 5.5);
        x += colWidths.shop_owner;
        doc.text(truncate(row.shop_name, 18), x, y + 5.5);
        x += colWidths.shop_name;
        doc.text(truncate(row.phone, 15), x, y + 5.5);
        x += colWidths.phone;
        doc.text(truncate(row.year, 8), x, y + 5.5);
        x += colWidths.year;
        doc.text(truncate(row.months, 18), x, y + 5.5);
        x += colWidths.months;
        doc.text(truncate(row.cash, 15), x, y + 5.5);
        x += colWidths.cash;
        doc.text(truncate(row.date, 12), x, y + 5.5);

        y += 8;
      });

      // Summary section
      y += 5;
      if (y > pageHeight - 60) {
        addFooter(currentPage, totalPages);
        doc.addPage();
        currentPage++;
        addLetterhead();
        y = 100;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 139);
      doc.text(`Total Shops: ${data.length}`, startX, y);
      
      const totalCash = data.reduce((sum, entry) => {
        return sum + entry.funds.reduce((s, f) => s + (f.cash || 0), 0);
      }, 0);
      
      doc.text(`Total Cash: LKR ${totalCash.toFixed(2)}`, startX + 60, y);

      addFooter(currentPage, totalPages);

    } else {
      // TABLE FORMAT for single shop
      const entry = data[0];
      const user = entry.user;
      const funds = entry.funds || [];

      addLetterhead();

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(40, 40, 40);
      const titleText = title.toUpperCase();
      doc.text(titleText, pageWidth / 2, 90, { align: 'center' });

      let y = 105;

      // Shop Details Header
      doc.setFillColor(240, 248, 255);
      doc.rect(15, y - 3, pageWidth - 30, 18, 'F');
      doc.setLineWidth(0.8);
      doc.setDrawColor(0, 0, 139);
      doc.rect(15, y - 3, pageWidth - 30, 18);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 139);
      doc.text('SHOP INFORMATION', 20, y + 8);

      y += 25;

      // Shop Details in 2 columns
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);

      const shopDetails = [
        { label: 'Registration No', value: user.reg_no },
        { label: 'Shop Owner Name', value: user.shop_owner_name },
        { label: 'Shop Name', value: user.shop_name },
        { label: 'Phone Number', value: user.phone_number },
        { label: 'Created Date', value: new Date(user.created_at).toLocaleDateString('en-GB') }
      ];

      let leftY = y;
      let rightY = y;
      shopDetails.forEach((detail, idx) => {
        const isLeft = idx % 2 === 0;
        const x = isLeft ? 25 : pageWidth / 2 + 10;
        const currentY = isLeft ? leftY : rightY;

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text(`${detail.label}:`, x, currentY);

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        const value = String(detail.value || 'N/A');
        doc.text(value.length > 35 ? value.substring(0, 32) + '...' : value, x + 45, currentY);

        if (isLeft) {
          leftY += 10;
        } else {
          rightY += 10;
        }
      });

      y = Math.max(leftY, rightY) + 15;

      // Funds Payment Table
      if (funds.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 139);
        doc.text('PAYMENT HISTORY', 20, y);
        y += 10;

        // Table configuration for individual shop
        const startX = 15;
        const tableWidth = pageWidth - 30;
        const colWidths2 = {
          no: 15,
          year: 25,
          months: 70,
          cash: 35,
          date: 35
        };

        // Draw table header
        doc.setFillColor(0, 0, 139);
        doc.rect(startX, y, tableWidth, 10, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(255, 255, 255);

        let x = startX + 2;
        doc.text('No.', x, y + 7);
        x += colWidths2.no;
        doc.text('Year', x, y + 7);
        x += colWidths2.year;
        doc.text('Months Paid', x, y + 7);
        x += colWidths2.months;
        doc.text('Cash Amount', x, y + 7);
        x += colWidths2.cash;
        doc.text('Payment Date', x, y + 7);

        y += 10;

        // Draw table rows
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(60, 60, 60);

        let totalShopCash = 0;

        funds.forEach((fund, idx) => {
          // Check if we need a new page
          if (y > pageHeight - 60) {
            addFooter(1, Math.ceil(funds.length / 15));
            doc.addPage();
            addLetterhead();
            y = 100;
          }

          // Alternate row colors
          if (idx % 2 === 0) {
            doc.setFillColor(248, 249, 250);
            doc.rect(startX, y, tableWidth, 10, 'F');
          }

          // Draw cell borders
          doc.setDrawColor(220, 220, 220);
          doc.setLineWidth(0.1);
          
          // Vertical lines
          x = startX;
          for (let i = 0; i <= Object.keys(colWidths2).length; i++) {
            doc.line(x, y, x, y + 10);
            if (i < Object.keys(colWidths2).length) {
              x += Object.values(colWidths2)[i];
            }
          }
          
          // Horizontal line
          doc.line(startX, y + 10, startX + tableWidth, y + 10);

          // Add text content
          x = startX + 2;
          
          doc.text(String(idx + 1), x, y + 6.5);
          x += colWidths2.no;
          
          doc.text(String(fund.year || 'N/A'), x, y + 6.5);
          x += colWidths2.year;
          
          const monthsText = fund.month ? fund.month.map(m => getMonthName(m)).join(', ') : 'N/A';
          const truncatedMonths = monthsText.length > 40 ? monthsText.substring(0, 37) + '...' : monthsText;
          doc.text(truncatedMonths, x, y + 6.5);
          x += colWidths2.months;
          
          doc.text(`LKR ${fund.cash || 0}`, x, y + 6.5);
          x += colWidths2.cash;
          
          doc.text(new Date(fund.created_at).toLocaleDateString('en-GB'), x, y + 6.5);

          totalShopCash += fund.cash || 0;
          y += 10;
        });

        // Total row
        y += 5;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 139);
        
        doc.setFillColor(230, 240, 255);
        doc.rect(startX, y, tableWidth, 12, 'F');
        doc.setDrawColor(0, 0, 139);
        doc.setLineWidth(0.5);
        doc.rect(startX, y, tableWidth, 12);

        doc.text('TOTAL PAYMENTS:', startX + 5, y + 8);
        doc.text(`${funds.length} Transactions`, startX + 55, y + 8);
        doc.text(`TOTAL CASH: LKR ${totalShopCash.toFixed(2)}`, startX + tableWidth - 75, y + 8);

      } else {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('No payment records found for this shop.', 25, y);
      }

      addFooter(1, 1);
    }

    const timestamp = new Date().toISOString().split('T')[0];
    const fileName = `${companyInfo.name}_${title.replace(/\s+/g, '_')}_${timestamp}.pdf`;

    doc.save(fileName);
    alert(`Professional report "${fileName}" downloaded successfully!`);

  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Error generating PDF. Please try again.');
  }
};

  // ------------------- DOWNLOAD FUNCTIONS -------------------
  const handleDownloadAll = () => generatePDF(fundsData, 'Complete Shop Funds Directory Report');

  // For single, flatten to one entry
  const handleDownloadSingle = (entry) => {
    const singleData = [{ user: entry.user, funds: entry.funds }];
    generatePDF(singleData, `Individual Shop Funds Report - ${entry.user.shop_name || entry.user.shop_owner_name}`);
  };

  // ------------------- FILTERED DATA -------------------
  const filteredFundsData = fundsData.filter(entry => {
    const userMatch = 
      (entry.user.shop_owner_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
      (entry.user.shop_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
      (entry.user.phone_number?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
      (entry.user.reg_no?.toString() || '').includes(searchTerm);
    
    const fundsMatch = entry.funds.some(f => 
      f.year.toString().includes(searchTerm) ||
      f.month.some(m => m.toString().includes(searchTerm)) ||
      f.cash.toString().includes(searchTerm)
    );
    
    return userMatch || fundsMatch;
  });

  // Flatten for table display (one row per fund, repeat user info)
  const flattenedData = filteredFundsData.flatMap(entry =>
    entry.funds.length > 0
      ? entry.funds.map(fund => ({ 
          ...entry.user, 
          ...fund, 
          funds_created_at: fund.created_at 
        }))
      : [{ 
          ...entry.user, 
          year: 'N/A', 
          month: [], 
          cash: 0, 
          funds_created_at: entry.user.created_at 
        }]
  );

  // ------------------- RENDER -------------------
  if (loading) {
    return (
      <div className="funds-section" id="funds-section">
        <Nav />
        <div className="title-container">
          <h2 className="Title">Shop Funds Details</h2>
          <p className="subtitle">{companyInfo.name} - {companyInfo.tagline}</p>
        </div>
        <div style={{ textAlign: 'center', padding: '50px' }}>Loading funds data...</div>
      </div>
    );
  }

  return (
    <div className="funds-section" id="funds-section">
      <Nav />
      <div className="title-container">
        <h2 className="Title">Shop Funds Details</h2>
        <p className="subtitle">{companyInfo.name} - {companyInfo.tagline}</p>
      </div>
      <div className="search-bar">
        <input
          type="text"
          placeholder="🔍 Search by Shop Owner Name, Shop Name, Phone, Reg. No, Year, Month, or Cash..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
        />
      </div>
      {/* Enhanced Download Options */}
      <div className="download-options professional-section">
        <h3>📄 Professional Report Generation</h3>
        <p>Select the fields to include in your professional letterhead report:</p>
        <div className="field-checkboxes">
          {Object.keys(selectedFields).map(field => (
            <label key={field} className="checkbox-label">
              <input
                type="checkbox"
                checked={selectedFields[field]}
                onChange={() => setSelectedFields(prev => ({ ...prev, [field]: !prev[field] }))}
              />
              <span>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</span>
            </label>
          ))}
        </div>
        <div className="download-buttons">
          <button className="download-all-btn" onClick={handleDownloadAll}>
            📊 Download Complete Funds Directory ({fundsData.length} shops)
          </button>
          <p className="download-note">
            Reports include professional letterhead with {companyInfo.name} logo, contact details, and formatted layouts.
          </p>
        </div>
      </div>
      {/* Funds Table */}
      <div className="funds-table-container">
        <div className="table-header">
          <span className="table-user-count">👥 Total Shops: {fundsData.length}</span>
          <span className="filtered-count">
            {searchTerm && `(Showing ${filteredFundsData.length} filtered results)`}
          </span>
        </div>
        <table className="funds-table">
          <thead>
            <tr>
              <th>Reg. No</th>
              <th>Shop Owner Name</th>
              <th>Shop Name</th>
              <th>Phone Number</th>
              <th>Year</th>
              <th>Months</th>
              <th>Cash (LKR)</th>
              <th>Funds Added At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {flattenedData.map((row, idx) => (
              <tr key={`${row.reg_no}-${row._id || row.created_at}-${idx}`}>
                <td><strong>{row.reg_no}</strong></td>
                <td>{row.shop_owner_name}</td>
                <td>{row.shop_name}</td>
                <td>{row.phone_number}</td>
                <td>{row.year || 'N/A'}</td>
                <td>{Array.isArray(row.month) && row.month.length > 0 ? row.month.join(', ') : 'N/A'}</td>
                <td>{row.cash ? `LKR ${row.cash}` : 'N/A'}</td>
                <td>{row.funds_created_at ? new Date(row.funds_created_at).toLocaleDateString('en-GB') : new Date(row.created_at).toLocaleDateString('en-GB')}</td>
                <td className="actions-cell">
                  <button 
                    className="action-btn download-btn" 
                    onClick={() => handleDownloadSingle(fundsData.find(d => d.user.reg_no === row.reg_no))} 
                    title="Download Shop Funds Report"
                  >
                    📄
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {filteredFundsData.length === 0 && (
          <div className="no-users-message">
            <p>📭 No funds details found matching your search criteria.</p>
            {searchTerm && (
              <button className="clear-search-btn" onClick={() => setSearchTerm('')}>
                Clear Search
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default FundsManagement;