// FundsManagement.jsx (New file)
import React, { useState, useEffect } from 'react';
import Nav from '../Nav/Nav';
import axios from 'axios';
import jsPDF from 'jspdf';
import './FundsManagement.css';

const URL = 'http://localhost:5000/funds'; // Assume new backend endpoint for joined data

function FundsManagement() {
  // ------------------- STATES -------------------
  const [fundsData, setFundsData] = useState([]); // Array of {user: {...}, funds: [...]}
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFields, setSelectedFields] = useState({
    reg_no: true,
    shop_owner_name: true,
    shop_name: true,
    phone_number: true,
    created_at: true,
    year: true,
    month: true,
    cash: true,
    funds_created_at: true
  });
  // No add/edit/delete for this view, as it's read-only details

  // ------------------- COMPANY INFORMATION -------------------
  const companyInfo = {
    name: 'Dompe',
    tagline: 'Dompe',
    address: ['No/346, Madalanda, Dompe,', 'Colombo, Sri Lanka'],
    phone: '+94 000 000 0000',
    email: 'test@gmail.com',
    website: 'www.test.com'
  };

  // ------------------- FETCH JOINED DATA -------------------
  const fetchFundsData = async () => {
    try {
      const res = await axios.get(URL);
      setFundsData(res.data.shops || []); // Assume backend returns {shops: [{user: {}, funds: []}]}
    } catch (err) {
      console.error('Error fetching funds data:', err);
      setFundsData([]);
    }
  };

  useEffect(() => {
    fetchFundsData();
  }, []);

  // ------------------- LOGO CONVERSION -------------------
  const getLogoAsBase64 = () => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        const base64 = canvas.toDataURL('image/png');
        resolve(base64);
      };
      img.onerror = () => {
        console.warn('Could not load logo, proceeding without it');
        resolve(null);
      };
      img.src = '/logo192.png';
    });
  };

  // ------------------- PROFESSIONAL PDF GENERATION -------------------
  const generatePDF = async (data, title) => {
    if (!data.length) return alert('No funds data to download!');

    try {
      const logoBase64 = await getLogoAsBase64();
   
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
   
      // Function to add professional letterhead
      const addLetterhead = () => {
        if (logoBase64) {
          doc.addImage(logoBase64, 'PNG', 15, 10, 30, 30);
        }
     
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(28);
        doc.setTextColor(0, 0, 139);
        doc.text(companyInfo.name, logoBase64 ? 55 : pageWidth / 2, 25, { align: logoBase64 ? 'left' : 'center' });
     
        doc.setFontSize(12);
        doc.setTextColor(0, 128, 255);
        doc.text(companyInfo.tagline, logoBase64 ? 55 : pageWidth / 2, 35, { align: logoBase64 ? 'left' : 'center' });
     
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
     
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text('Address:', 15, 50);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        companyInfo.address.forEach((line, index) => {
          doc.text(line, 15, 57 + (index * 7));
        });
     
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 139);
        doc.text('Contact Information:', pageWidth - 85, 50);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        doc.text(`Phone: ${companyInfo.phone}`, pageWidth - 85, 57);
        doc.text(`Email: ${companyInfo.email}`, pageWidth - 85, 64);
        doc.text(`Website: ${companyInfo.website}`, pageWidth - 85, 71);
     
        doc.setLineWidth(1.5);
        doc.setDrawColor(0, 0, 139);
        doc.line(15, 80, pageWidth - 15, 80);
     
        doc.setLineWidth(0.8);
        doc.setDrawColor(0, 128, 255);
        doc.line(15, 82, pageWidth - 15, 82);
      };
   
      const addFooter = (pageNum, totalPages) => {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
     
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);
     
        const footerText = `This document is generated by ${companyInfo.name} Funds Management System`;
        doc.text(footerText, pageWidth / 2, pageHeight - 22, { align: 'center' });
     
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 15, pageHeight - 12, { align: 'right' });
        const genDate = new Date().toLocaleDateString('en-GB');
        const genTime = new Date().toLocaleTimeString('en-GB', { hour12: false });
        doc.text(`Generated: ${genDate} at ${genTime}`, 15, pageHeight - 12);
     
        doc.setTextColor(0, 0, 139);
        doc.text(companyInfo.website, pageWidth / 2, pageHeight - 5, { align: 'center' });
      };
   
      let totalPages = 1;
      let tempY = 95;
      data.forEach(() => {
        let fieldsCount = Object.keys(selectedFields).filter(field => selectedFields[field]).length;
        let entryHeight = Math.ceil(fieldsCount / 2) * 12 + 35 + (data.length > 1 ? 20 : 0); // Extra for funds array
     
        if (tempY + entryHeight > pageHeight - 45) {
          totalPages++;
          tempY = 95;
        }
        tempY += entryHeight;
      });
   
      let currentPage = 1;
      let y = 95;
   
      addLetterhead();
   
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(40, 40, 40);
      const titleText = title.toUpperCase();
      doc.text(titleText, pageWidth / 2, 90, { align: 'center' });
   
      data.forEach((entry, idx) => {
        const user = entry.user;
        const funds = entry.funds || [];
        let fieldsCount = Object.keys(selectedFields).filter(field => selectedFields[field]).length;
        let entryHeight = Math.ceil(fieldsCount / 2) * 12 + 35 + (funds.length * 15);
     
        if (y + entryHeight > pageHeight - 45) {
          addFooter(currentPage, totalPages);
          doc.addPage();
          currentPage++;
          addLetterhead();
          y = 95;
        }
     
        doc.setFillColor(240, 248, 255);
        doc.rect(15, y - 3, pageWidth - 30, 18, 'F');
     
        doc.setLineWidth(0.8);
        doc.setDrawColor(0, 0, 139);
        doc.rect(15, y - 3, pageWidth - 30, 18);
     
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 139);
        doc.text(`SHOP FUNDS RECORD #${String(idx + 1).padStart(3, '0')}`, 20, y + 8);
     
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(`Reg. No: ${user.reg_no || 'N/A'}`, pageWidth - 70, y + 8);
     
        y += 25;
     
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
     
        let leftY = y;
        let rightY = y;
        let isLeft = true;
     
        // User fields
        Object.keys(selectedFields).forEach(field => {
          if (selectedFields[field] && ['reg_no', 'shop_owner_name', 'shop_name', 'phone_number', 'created_at'].includes(field)) {
            let label = field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase());
            let value = user[field] || 'N/A';
         
            if (field === 'created_at') {
              value = new Date(value).toLocaleDateString('en-GB');
            }
         
            if (typeof value === 'string' && value.length > 35) {
              value = value.substring(0, 32) + '...';
            }
         
            const x = isLeft ? 25 : pageWidth / 2 + 10;
            const currentY = isLeft ? leftY : rightY;
         
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0, 0, 139);
            doc.text(`${label}:`, x, currentY);
         
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(60, 60, 60);
            doc.text(String(value), x + 50, currentY);
         
            if (isLeft) {
              leftY += 12;
            } else {
              rightY += 12;
            }
         
            isLeft = !isLeft;
          }
        });
     
        y = Math.max(leftY, rightY) + 10;
     
        // Funds details
        if (funds.length > 0) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(12);
          doc.setTextColor(0, 0, 139);
          doc.text('Funds Added:', 25, y);
          y += 15;
     
          funds.forEach((fund, fIdx) => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            doc.setTextColor(60, 60, 60);
            doc.text(`Year: ${fund.year}, Months: [${fund.month.join(', ')}], Cash: LKR ${fund.cash}, Date: ${new Date(fund.created_at).toLocaleDateString('en-GB')}`, 25, y);
            y += 12;
          });
        } else {
          doc.setFont('helvetica', 'italic');
          doc.setFontSize(10);
          doc.setTextColor(100, 100, 100);
          doc.text('No funds added yet.', 25, y);
          y += 15;
        }
     
        if (idx < data.length - 1) {
          doc.setLineWidth(0.3);
          doc.setDrawColor(220, 220, 220);
          doc.line(25, y - 5, pageWidth - 25, y - 5);
          y += 15;
        }
      });
   
      addFooter(currentPage, totalPages);
   
      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `${companyInfo.name}_${title.replace(/\s+/g, '_')}_${timestamp}.pdf`;
   
      doc.save(fileName);
      alert(`Professional report "${fileName}" downloaded successfully!`);
   
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    }
  };

  // ------------------- DOWNLOAD FUNCTIONS -------------------
  const handleDownloadAll = () => generatePDF(fundsData, 'Complete Shop Funds Directory Report');

  // For single, flatten to one entry
  const handleDownloadSingle = (entry) => {
    const singleData = [{ user: entry.user, funds: entry.funds }];
    generatePDF(singleData, `Individual Shop Funds Report - ${entry.user.shop_name || entry.user.shop_owner_name}`);
  };

  // ------------------- FILTERED DATA -------------------
  const filteredFundsData = fundsData.filter(entry =>
    (entry.user.shop_owner_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (entry.user.shop_name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (entry.user.phone_number?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
    (entry.user.reg_no?.toString() || '').includes(searchTerm) ||
    (entry.funds.some(f => f.year.toString().includes(searchTerm)) || entry.funds.some(f => f.month.some(m => m.toString().includes(searchTerm))) || entry.funds.some(f => f.cash.toString().includes(searchTerm)))
  );

  // Flatten for table display (one row per fund, repeat user info)
  const flattenedData = filteredFundsData.flatMap(entry => 
    entry.funds.length > 0 
      ? entry.funds.map(fund => ({ ...entry.user, ...fund, funds_created_at: fund.created_at }))
      : [{ ...entry.user, year: 'N/A', month: [], cash: 0, funds_created_at: entry.user.created_at }]
  );

  // ------------------- RENDER -------------------
  return (
    <div className="funds-section" id="funds-section">
      <Nav />
      <div className="title-container">
        <h2 className="Title">Shop Funds Details</h2>
        <p className="subtitle">{companyInfo.name} - {companyInfo.tagline}</p>
      </div>
      <div className="search-bar">
        <input
          type="text"
          placeholder="🔍 Search by Shop Owner Name, Shop Name, Phone, Reg. No, Year, Month, or Cash..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
        />
      </div>
      {/* Enhanced Download Options */}
      <div className="download-options professional-section">
        <h3>📄 Professional Report Generation</h3>
        <p>Select the fields to include in your professional letterhead report:</p>
        <div className="field-checkboxes">
          {Object.keys(selectedFields).map(field => (
            <label key={field} className="checkbox-label">
              <input
                type="checkbox"
                checked={selectedFields[field]}
                onChange={() => setSelectedFields(prev => ({ ...prev, [field]: !prev[field] }))}
              />
              <span>{field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</span>
            </label>
          ))}
        </div>
        <div className="download-buttons">
          <button className="download-all-btn" onClick={handleDownloadAll}>
            📊 Download Complete Funds Directory ({fundsData.length} shops)
          </button>
          <p className="download-note">
            Reports include professional letterhead with {companyInfo.name} logo, contact details, and formatted layouts.
          </p>
        </div>
      </div>
      {/* Funds Table */}
      <div className="funds-table-container">
        <div className="table-header">
          <span className="table-user-count">👥 Total Shops: {fundsData.length}</span>
          <span className="filtered-count">
            {searchTerm && `(Showing ${filteredFundsData.length} filtered results)`}
          </span>
        </div>
        <table className="funds-table">
          <thead>
            <tr>
              <th>Reg. No</th>
              <th>Shop Owner Name</th>
              <th>Shop Name</th>
              <th>Phone Number</th>
              <th>Year</th>
              <th>Months</th>
              <th>Cash (LKR)</th>
              <th>Funds Added At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {flattenedData.map((row, idx) => (
              <tr key={`${row.reg_no}-${row._id || idx}`}>
                <td><strong>{row.reg_no}</strong></td>
                <td>{row.shop_owner_name}</td>
                <td>{row.shop_name}</td>
                <td>{row.phone_number}</td>
                <td>{row.year || 'N/A'}</td>
                <td>{Array.isArray(row.month) ? row.month.join(', ') : 'N/A'}</td>
                <td>{row.cash ? `LKR ${row.cash}` : 'N/A'}</td>
                <td>{row.funds_created_at ? new Date(row.funds_created_at).toLocaleDateString('en-GB') : new Date(row.created_at).toLocaleDateString('en-GB')}</td>
                <td className="actions-cell">
                  <button className="action-btn download-btn" onClick={() => handleDownloadSingle(fundsData.find(d => d.user.reg_no === row.reg_no))} title="Download Shop Funds Report">
                    📄
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
     
        {filteredFundsData.length === 0 && (
          <div className="no-users-message">
            <p>📭 No funds details found matching your search criteria.</p>
            {searchTerm && (
              <button className="clear-search-btn" onClick={() => setSearchTerm('')}>
                Clear Search
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default FundsManagement;